### ISSUE TITLE
flutter 2.0.2编译失败

### ISSUE THREAD

**Issue by ismlsmile** [CNAD666/flutter_use#1]
windows上失败日志：
/C:/flutter/.pub-cache/git/flutter_toolkit-8ae48d60794a4998f82cc685aadef2d5b5eba4a1/lib/src/net/src/interceptor/error_interceptor.dart(9,10): error G76A9B1F6: The method 'ErrorInterceptor.onError' has fewer positional arguments than those of overridden method 'Interceptor.onError'. [D:\Code\flutter_use\build\windows\flutter\flutter_assemble.vcxproj]
/C:/flutter/.pub-cache/git/flutter_toolkit-8ae48d60794a4998f82cc685aadef2d5b5eba4a1/lib/src/net/src/interceptor/error_interceptor.dart(15,25): error G4117F63E: Too few positional arguments: 2 required, 1 given. [D:\Code\flutter_use\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: “D:\Code\flutter_use\build\windows\CMakeFiles\28380f36d5341bfcdb8c161a898f2e6f\flutter_windows.dll.rule;D:\Code\flutter_use\build\windows\CMakeFiles\b8af8cce732b11c57a701b8e807268af\flutter_assemble.rule”的自定义生成已退 出，代码为 1。 [D:\Code\flutter_use\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Build process failed.

**Comment by xdd666t** [comment]
> windows上失败日志：
> /C:/flutter/.pub-cache/git/flutter_toolkit-8ae48d60794a4998f82cc685aadef2d5b5eba4a1/lib/src/net/src/interceptor/error_interceptor.dart(9,10): error G76A9B1F6: The method 'ErrorInterceptor.onError' has fewer positional arguments than those of overridden method 'Interceptor.onError'. [D:\Code\flutter_use\build\windows\flutter\flutter_assemble.vcxproj]
> /C:/flutter/.pub-cache/git/flutter_toolkit-8ae48d60794a4998f82cc685aadef2d5b5eba4a1/lib/src/net/src/interceptor/error_interceptor.dart(15,25): error G4117F63E: Too few positional arguments: 2 required, 1 given. [D:\Code\flutter_use\build\windows\flutter\flutter_assemble.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: “D:\Code\flutter_use\build\windows\CMakeFiles\28380f36d5341bfcdb8c161a898f2e6f\flutter_windows.dll.rule;D:\Code\flutter_use\build\windows\CMakeFiles\b8af8cce732b11c57a701b8e807268af\flutter_assemble.rule”的自定义生成已退 出，代码为 1。 [D:\Code\flutter_use\build\windows\flutter\flutter_assemble.vcxproj]
> Building Windows application...
> Build process failed.

你这个build文件夹里面存在一些文件冲突，执行下命令
```
flutter clean
```
然后pub get下，再运行项目

**Comment by ismlsmile** [comment]
换了台机器还是报错。我看了下，是https://github.com/CNAD666/flutter_toolkit这个库的问题，该库的lib/src/net/src/interceptor/error_interceptor.dart这个文件的第9行：
![image](https://user-images.githubusercontent.com/1876179/111584892-6ff70c00-87f9-11eb-9cbe-82963a5bddf3.png)

参数只有一个，但其基类中的这个方法是：
![image](https://user-images.githubusercontent.com/1876179/111584934-856c3600-87f9-11eb-820e-9f2d740bfc43.png)

参数有两个。参数数量不一致，导致覆盖失败，这是报错的原因。

**Comment by ismlsmile** [comment]
我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过

**Comment by xdd666t** [comment]
> 换了台机器还是报错。我看了下，是[https://github.com/CNAD666/flutter_toolkit这个库的问题，该库的lib/src/net/src/interceptor/error_interceptor.dart这个文件的第9行：](https://github.com/CNAD666/flutter_toolkit%E8%BF%99%E4%B8%AA%E5%BA%93%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E8%AF%A5%E5%BA%93%E7%9A%84lib/src/net/src/interceptor/error_interceptor.dart%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%E7%9A%84%E7%AC%AC9%E8%A1%8C%EF%BC%9A)
> ![image](https://user-images.githubusercontent.com/1876179/111584892-6ff70c00-87f9-11eb-9cbe-82963a5bddf3.png)
> 
> 参数只有一个，但其基类中的这个方法是：
> ![image](https://user-images.githubusercontent.com/1876179/111584934-856c3600-87f9-11eb-820e-9f2d740bfc43.png)
> 
> 参数有两个。参数数量不一致，导致覆盖失败，这是报错的原因。

![image](https://user-images.githubusercontent.com/35656085/111585547-71750400-87fa-11eb-9ff9-2fd42c8c08d9.png)

**Comment by xdd666t** [comment]
> 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过

看到了，我来改下

**Comment by tomorrowDolol** [comment]
> > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> 
> 看到了，我来改下

-.-是直接去掉了吗

**Comment by xdd666t** [comment]
可以了，你跑下 pub upgrade 就行了

**Comment by xdd666t** [comment]
> > > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> > 
> > 
> > 看到了，我来改下
> 
> -.-是直接去掉了吗

我远程依赖库里面依赖了dio，这个项目没必要加dio包了

**Comment by tomorrowDolol** [comment]
> > > > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> > > 
> > > 
> > > 看到了，我来改下
> > 
> > 
> > -.-是直接去掉了吗
> 
> 我远程依赖库里面依赖了dio，这个项目没必要加dio包了

不懂就问...如果想强制依赖4.0.0beta7是怎么写呢...搜了一下搜索技术不过关...

**Comment by ismlsmile** [comment]
> > > > > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> > > > 
> > > > 
> > > > 看到了，我来改下
> > > 
> > > 
> > > -.-是直接去掉了吗
> > 
> > 
> > 我远程依赖库里面依赖了dio，这个项目没必要加dio包了
> 
> 不懂就问...如果想强制依赖4.0.0beta7是怎么写呢...搜了一下搜索技术不过关...

去掉"^"

**Comment by ismlsmile** [comment]
> 可以了，你跑下 pub upgrade 就行了

测试通过。不过里面的图片都挂了
HTTP request failed, statusCode: 403, https://cdn.jsdelivr.net/gh/CNAD666/MyData/pic/flutter/norm/20210306210545.jpeg

这个issue我先关闭了吧。

**Comment by xdd666t** [comment]
> > 可以了，你跑下 pub upgrade 就行了
> 
> 测试通过。不过里面的图片都挂了
> HTTP request failed, statusCode: 403, https://cdn.jsdelivr.net/gh/CNAD666/MyData/pic/flutter/norm/20210306210545.jpeg
> 
> 这个issue我先关闭了吧。

图片没挂啊，网的问题吧，遇事不决，开下vpn
![image](https://user-images.githubusercontent.com/35656085/111588348-67550480-87fe-11eb-8c50-b2beab583055.png)

**Comment by ismlsmile** [comment]
> > > 可以了，你跑下 pub upgrade 就行了
> > 
> > 
> > 测试通过。不过里面的图片都挂了
> > HTTP request failed, statusCode: 403, https://cdn.jsdelivr.net/gh/CNAD666/MyData/pic/flutter/norm/20210306210545.jpeg
> > 这个issue我先关闭了吧。
> 
> 图片没挂啊，网的问题吧，遇事不决，开下vpn
> ![image](https://user-images.githubusercontent.com/35656085/111588348-67550480-87fe-11eb-8c50-b2beab583055.png)

早开VPN了，否则我咋上到这里来的。我这里报这个错：
Package size exceeded the configured limit of 50 MB. Try https://github.com/CNAD666/MyData/tree/master/pic/flutter/norm/20210306210545.jpeg instead.

**Comment by tomorrowDolol** [comment]
> > > > > > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> > > > > 
> > > > > 
> > > > > 看到了，我来改下
> > > > 
> > > > 
> > > > -.-是直接去掉了吗
> > > 
> > > 
> > > 我远程依赖库里面依赖了dio，这个项目没必要加dio包了
> > 
> > 
> > 不懂就问...如果想强制依赖4.0.0beta7是怎么写呢...搜了一下搜索技术不过关...
> 
> 去掉"^"

好的谢谢。知识点+1
重新跑后，还是要先去掉http.dart 以及window_size.dart里面的内容，终于可以跑起来了~~

**Comment by xdd666t** [comment]
图片失效的问题，太鸡儿坑了，cdn.jsdelivr加速，仓库包超过50兆，居然直接拒绝访问
项目中的图片链接全部更新了，你可以pull下代码，跑下看看

**Comment by xdd666t** [comment]
> > > > > > > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> > > > > > 
> > > > > > 
> > > > > > 看到了，我来改下
> > > > > 
> > > > > 
> > > > > -.-是直接去掉了吗
> > > > 
> > > > 
> > > > 我远程依赖库里面依赖了dio，这个项目没必要加dio包了
> > > 
> > > 
> > > 不懂就问...如果想强制依赖4.0.0beta7是怎么写呢...搜了一下搜索技术不过关...
> > 
> > 去掉"^"
> 
> 好的谢谢。知识点+1
> 重新跑后，还是要先去掉http.dart 以及window_size.dart里面的内容，终于可以跑起来了~~

老哥，http的，你不用去掉啊，这个我已经改好了，你pull下我最近代码，然后你跑下 pub upgrade就行。
window_size插件会导致在windows电脑打包报错的解决方法，我写在了readme里面，设置下就行了，系统限制我没法在代码上解决

**Comment by tomorrowDolol** [comment]
> > > > > > > > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> > > > > > > 
> > > > > > > 
> > > > > > > 看到了，我来改下
> > > > > > 
> > > > > > 
> > > > > > -.-是直接去掉了吗
> > > > > 
> > > > > 
> > > > > 我远程依赖库里面依赖了dio，这个项目没必要加dio包了
> > > > 
> > > > 
> > > > 不懂就问...如果想强制依赖4.0.0beta7是怎么写呢...搜了一下搜索技术不过关...
> > > 
> > > 
> > > 去掉"^"
> > 
> > 
> > 好的谢谢。知识点+1
> > 重新跑后，还是要先去掉http.dart 以及window_size.dart里面的内容，终于可以跑起来了~~
> 
> 老哥，http的，你不用去掉啊，这个我已经改好了，你pull下我最近代码，然后你跑下 pub upgrade就行。
> window_size插件会导致在windows电脑打包报错的解决方法，我写在了readme里面，设置下就行了，系统限制我没法在代码上解决

大佬，http里面有使用到dio啊。不注释跑不了。我看到有依赖url: https://github.com/CNAD666/flutter_toolkit.git 但是这个我查看了一下，获取不了。

**Comment by xdd666t** [comment]
> > > > > > > > > 我再看了下，dio发布了新版本4.0.0-prev1，里面是两个参数的。原来的4.0.0-beta7是一个参数。修改了pubspec.yaml，强制依赖4.0.0-beta7，编译可以通过
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 看到了，我来改下
> > > > > > > 
> > > > > > > 
> > > > > > > -.-是直接去掉了吗
> > > > > > 
> > > > > > 
> > > > > > 我远程依赖库里面依赖了dio，这个项目没必要加dio包了
> > > > > 
> > > > > 
> > > > > 不懂就问...如果想强制依赖4.0.0beta7是怎么写呢...搜了一下搜索技术不过关...
> > > > 
> > > > 
> > > > 去掉"^"
> > > 
> > > 
> > > 好的谢谢。知识点+1
> > > 重新跑后，还是要先去掉http.dart 以及window_size.dart里面的内容，终于可以跑起来了~~
> > 
> > 
> > 老哥，http的，你不用去掉啊，这个我已经改好了，你pull下我最近代码，然后你跑下 pub upgrade就行。
> > window_size插件会导致在windows电脑打包报错的解决方法，我写在了readme里面，设置下就行了，系统限制我没法在代码上解决
> 
> 大佬，http里面有使用到dio啊。不注释跑不了。我看到有依赖url: https://github.com/CNAD666/flutter_toolkit.git 但是这个我查看了一下，获取不了。

逼我出绝招，你再拉下代码，然后跑下试试，这个插件我已经更新到pub上了

pub插件引用github上的，实际要用sstap开全局代理才能获取到

**Comment by ismlsmile** [comment]
> 图片失效的问题，太鸡儿坑了，cdn.jsdelivr加速，仓库包超过50兆，居然直接拒绝访问
> 项目中的图片链接全部更新了，你可以pull下代码，跑下看看

可以了
