### ISSUE TITLE
AutoUi初始化问题

### ISSUE THREAD

**Issue by huxiaobo** [CNAD666/flutter_use#3]
![image](https://user-images.githubusercontent.com/6804578/129876205-49cc75b7-52cc-401d-986d-a84a0f7586ea.png)

这里if (context != null) return;  岂不是永远不会执行下面的初始化代码

**Comment by xdd666t** [comment]
我靠，好大一bug
老哥，我已经改了，你可以pull下我的分支代码看看
![image](https://user-images.githubusercontent.com/35656085/129879067-acd0a218-d612-4225-9a70-50a9080e4d7c.png)

**Comment by huxiaobo** [comment]
OK  自学Flutter中...... 今天刚刚看完你写的GetX文章

**Comment by xdd666t** [comment]
> OK 自学Flutter中...... 今天刚刚看完你写的GetX文章

哈哈哈，加油
