### ISSUE TITLE
windows打包问题

### ISSUE THREAD

**Issue by huxiaobo** [CNAD666/flutter_use#4]
想问一下  windows打release包是如何打的   我打的包使用了sqflite_common_ffi  运行时无法创建数据库  不知道是打包问题还是需要怎么配置数据库

**Comment by huxiaobo** [comment]
解决了  发现是下载的sqlite3.dll 文件有问题   另外想请教下打包成exe安装文件是用的什么工具

**Comment by xdd666t** [comment]
我用的是CreateInstall：https://www.createinstall.com/
