### ISSUE TITLE
刚启动，白屏后会出现黑屏（黑屏中有一个小点），才出现首页

### ISSUE THREAD

**Issue by shisp** [CNAD666/flutter_use#9]
flutter初学者哈，不懂啥情况
Android Studio Koala | 2024.1.1
flutter3.22.2
dart3.4.3
![Screenshot_20240719_095615_com tao flutter_use](https://github.com/user-attachments/assets/e93fa367-4124-4afd-9d56-c19a2077c8e4)

**Comment by xdd666t** [comment]
这个是处理web端js分包导致的, 做了下兼容, 你可以再拉下代码看看, 已经解决了

**Comment by cjcj125125** [comment]
俺也一样
